# Generated by Django 4.1.4 on 2023-01-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30)),
                ('apt_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
