# Generated by Django 4.1.4 on 2023-01-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0003_login_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_table',
            name='apt_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
