# Generated by Django 4.1.4 on 2023-01-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0006_delete_login_table_remove_signup_table_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('apt_no', models.CharField(max_length=10)),
                ('amenity', models.CharField(max_length=30)),
                ('slot_no', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('partner_name', models.CharField(max_length=30)),
                ('partner_apt_no', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=10)),
            ],
        ),
    ]
