# Generated by Django 4.1.4 on 2023-01-18 11:55

import amenity_booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0008_remove_master_id_alter_master_apt_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='apt_no',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[amenity_booking.models.validate_apt_no]),
        ),
        migrations.AlterField(
            model_name='master',
            name='email',
            field=models.CharField(max_length=50, validators=[amenity_booking.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(max_length=10, validators=[amenity_booking.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='signup_table',
            name='apt_no',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='signup_table',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup_table',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='signup_table',
            name='username',
            field=models.CharField(max_length=16),
        ),
    ]
