# Generated by Django 4.1.4 on 2023-01-19 07:20

import amenity_booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0009_alter_master_apt_no_alter_master_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='amenity_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=30, validators=[amenity_booking.models.validate_amenity])),
                ('no_of_slots', models.IntegerField(validators=[amenity_booking.models.validate_slots])),
                ('set_activity_status', models.BooleanField(default=1)),
                ('test2', models.IntegerField(default=0)),
            ],
        ),
    ]
