# Generated by Django 4.1.4 on 2023-01-19 08:40

import amenity_booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0010_amenity_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='amenity_config_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=30, validators=[amenity_booking.models.validate_amenity])),
                ('no_of_slots', models.IntegerField(validators=[amenity_booking.models.validate_slots])),
            ],
        ),
        migrations.DeleteModel(
            name='amenity_table',
        ),
    ]
