# Generated by Django 4.1.4 on 2023-01-19 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amenity_booking', '0011_amenity_config_table_delete_amenity_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_table',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
