# Generated by Django 4.1.4 on 2023-01-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0012_signup_table_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_table',
            name='user',
        ),
    ]
