# Generated by Django 4.1.4 on 2023-01-20 06:22

import amenity_booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0013_remove_signup_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity_config_table',
            name='hours_active_from_6am',
            field=models.IntegerField(default=0, validators=[amenity_booking.models.validate_hours]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_table',
            name='username',
            field=models.CharField(default='nonee', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='apt_no',
            field=models.CharField(max_length=3, validators=[amenity_booking.models.validate_apt_no]),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='partner_apt_no',
            field=models.CharField(max_length=3, validators=[amenity_booking.models.validate_apt_no]),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='slot_no',
            field=models.IntegerField(validators=[amenity_booking.models.validate_slots]),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
