# Generated by Django 4.1.4 on 2023-01-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0014_amenity_config_table_hours_active_from_6am_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity_config_table',
            name='hours_active_from_6am',
        ),
        migrations.AddField(
            model_name='amenity_config_table',
            name='time1',
            field=models.BooleanField(default=False, verbose_name='6AM - 7AM'),
        ),
        migrations.AddField(
            model_name='amenity_config_table',
            name='time2',
            field=models.BooleanField(default=False, verbose_name='7AM - 8AM'),
        ),
        migrations.AddField(
            model_name='amenity_config_table',
            name='time3',
            field=models.BooleanField(default=False, verbose_name='8AM - 9AM'),
        ),
        migrations.AddField(
            model_name='amenity_config_table',
            name='time4',
            field=models.BooleanField(default=False, verbose_name='9AM - 10AM'),
        ),
    ]
