# Generated by Django 4.1.4 on 2023-01-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0019_delete_amenity_config_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_table',
            old_name='amenity',
            new_name='amenity_name',
        ),
        migrations.RemoveField(
            model_name='booking_table',
            name='slot_no',
        ),
        migrations.AddField(
            model_name='booking_table',
            name='slot',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='apt_no',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='partner_apt_no',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='payment_method',
            field=models.CharField(max_length=30),
        ),
    ]
