# Generated by Django 4.1.4 on 2023-01-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0020_rename_amenity_booking_table_amenity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='booking_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
