# Generated by Django 4.1.4 on 2023-01-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0021_booking_table_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50, null=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.IntegerField(choices=[('100', '100'), ('250', '250')])),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=30, null=True)),
            ],
        ),
    ]
