# Generated by Django 4.1.4 on 2023-01-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0023_booking_confirmation_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking_confirmation',
        ),
        migrations.AddField(
            model_name='booking_table',
            name='amount',
            field=models.IntegerField(choices=[('100', '100'), ('250', '250')], null=True),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=30, null=True),
        ),
    ]
