# Generated by Django 4.1.4 on 2023-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0024_delete_booking_confirmation_booking_table_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='amount',
            field=models.IntegerField(blank=True, choices=[('100', '100'), ('250', '250')], null=True),
        ),
    ]
