# Generated by Django 4.1.5 on 2023-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0027_alter_amenity_slots_slot_alter_booking_table_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity_slots',
            options={'verbose_name_plural': 'Amenity Slots Table'},
        ),
        migrations.AlterModelOptions(
            name='amenity_timings',
            options={'verbose_name_plural': 'Amenity Timing Table'},
        ),
        migrations.AlterModelOptions(
            name='amenity_type',
            options={'verbose_name_plural': 'Amenity Table'},
        ),
        migrations.AlterModelOptions(
            name='booking_table',
            options={'verbose_name_plural': 'Booking Table'},
        ),
        migrations.AlterModelOptions(
            name='contact_table',
            options={'verbose_name_plural': 'Contact Table'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name_plural': 'Master Table'},
        ),
        migrations.AlterModelOptions(
            name='signup_table',
            options={'verbose_name_plural': 'Signup Table'},
        ),
        migrations.AlterField(
            model_name='amenity_slots',
            name='slot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
