# Generated by Django 4.1.5 on 2023-01-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0028_alter_amenity_slots_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='amount',
            field=models.CharField(blank=True, choices=[('100', '100'), ('250', '250')], max_length=10, null=True),
        ),
    ]
