# Generated by Django 4.1.5 on 2023-02-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0029_alter_booking_table_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='book_time',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
