# Generated by Django 4.1.5 on 2023-02-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0030_booking_table_book_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='partner_apt_no',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='partner_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
