# Generated by Django 4.1.5 on 2023-02-24 02:16

import amenity_booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0032_uidtable_alter_amenity_type_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity_type',
            name='allow_multiple_bookings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenity_type',
            name='housing_space',
            field=models.IntegerField(default=0, validators=[amenity_booking.models.validate_space]),
        ),
    ]
