# Generated by Django 4.1.5 on 2023-02-24 03:51

import amenity_booking.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0034_alter_amenity_slots_slot_alter_amenity_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity_type',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[functools.partial(amenity_booking.models.validate_amenity, *(), **{})]),
        ),
    ]
