# Generated by Django 4.1.5 on 2023-02-24 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0038_alter_amenity_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='filled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amenity_booking.amenity_type')),
                ('amenity_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amenity_booking.amenity_slots')),
                ('amenity_timing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amenity_booking.amenity_timings')),
            ],
        ),
    ]
