# Generated by Django 4.1.5 on 2023-02-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0040_filled_available_space_filled_total_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filled',
            name='amenity_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
