# Generated by Django 4.1.5 on 2023-02-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0041_filled_amenity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filled',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
