# Generated by Django 4.1.5 on 2023-02-24 12:58

import amenity_booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0042_filled_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity_slots',
            name='amenity_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amenity_booking.amenity_type', validators=[amenity_booking.models.validate_slots]),
        ),
        migrations.CreateModel(
            name='amenity_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[amenity_booking.models.validate_date])),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amenity_booking.amenity_timings')),
            ],
            options={
                'verbose_name_plural': 'Amenity Maintenance Table',
            },
        ),
    ]
