# Generated by Django 4.1.5 on 2023-02-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0045_alter_amenity_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity_maintenance',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amenity_booking.amenity_slots'),
        ),
    ]
