# Generated by Django 4.1.5 on 2023-02-24 15:10

import amenity_booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0046_amenity_maintenance_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity_type',
            name='base_rate',
            field=models.IntegerField(default=0, validators=[amenity_booking.models.validate_space]),
        ),
        migrations.AddField(
            model_name='amenity_type',
            name='extra_rate_per_person',
            field=models.IntegerField(default=0, validators=[amenity_booking.models.validate_space]),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='space',
            field=models.IntegerField(default=0, validators=[amenity_booking.models.validate_space]),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='amount',
            field=models.IntegerField(default=0, validators=[amenity_booking.models.validate_space]),
        ),
    ]
