# Generated by Django 4.1.5 on 2023-02-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0048_alter_amenity_maintenance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity_maintenance',
            options={'verbose_name_plural': '8) Amenity Maintenance '},
        ),
        migrations.AlterModelOptions(
            name='filled',
            options={'verbose_name_plural': 'System Info 2'},
        ),
        migrations.AlterModelOptions(
            name='uidtable',
            options={'verbose_name_plural': 'System Info 1'},
        ),
    ]
