# Generated by Django 4.1.5 on 2023-02-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0049_alter_amenity_maintenance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity_maintenance',
            options={'verbose_name_plural': '8) Amenity Maintenance'},
        ),
    ]
