# Generated by Django 4.1.5 on 2023-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0050_alter_amenity_maintenance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity_type',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
