# Generated by Django 4.1.5 on 2023-02-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0051_alter_amenity_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity_slots',
            name='amenity_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amenity_booking.amenity_type'),
        ),
    ]
