# Generated by Django 4.1.5 on 2023-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0053_alter_amenity_maintenance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
