# Generated by Django 4.1.5 on 2023-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0054_alter_master_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
