# Generated by Django 4.1.5 on 2023-02-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0056_alter_signup_table_apt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity_maintenance',
            name='date',
            field=models.DateField(),
        ),
    ]
